-- MySQL Script generated by MySQL Workbench
-- Thu Aug 29 11:10:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza_time
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza_time
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza_time` DEFAULT CHARACTER SET utf8 ;
USE `pizza_time` ;

-- -----------------------------------------------------
-- Table `pizza_time`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_time`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(100) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `password` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_time`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_time`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('CARRY', 'SERVE', 'HOME') NOT NULL,
  `favorite` TINYINT NULL DEFAULT 0,
  `paid` TINYINT NOT NULL DEFAULT 0,
  `date` DATE NULL,
  `delivery_fee` DECIMAL(10,2) NULL,
  `tax` DECIMAL(10,2) NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `pizza_time`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_time`.`toppings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_time`.`toppings` (
  `topics_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`topics_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_time`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_time`.`pizza` (
  `pizza_id` INT NOT NULL AUTO_INCREMENT,
  `size` ENUM('S', 'M', 'L', 'XL') NOT NULL,
  `crust` ENUM('THIN', 'THICK', 'NORMAL') NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `orders_order_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`),
  INDEX `fk_pizza_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `pizza_time`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_time`.`pizza_has_toppings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_time`.`pizza_has_toppings` (
  `pizza_pizza_id` INT NOT NULL,
  `toppings_topics_id` INT NOT NULL,
  PRIMARY KEY (`pizza_pizza_id`, `toppings_topics_id`),
  INDEX `fk_pizza_has_toppings_toppings1_idx` (`toppings_topics_id` ASC) VISIBLE,
  INDEX `fk_pizza_has_toppings_pizza1_idx` (`pizza_pizza_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_has_toppings_pizza1`
    FOREIGN KEY (`pizza_pizza_id`)
    REFERENCES `pizza_time`.`pizza` (`pizza_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_toppings_toppings1`
    FOREIGN KEY (`toppings_topics_id`)
    REFERENCES `pizza_time`.`toppings` (`topics_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
